services:
  - type: web
    name: mental_health_app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run mental_health_app.py --server.port=$PORT --server.address=0.0.0.0