services:
  - type: web
    name: bipolar-app
    runtime: python
    pythonVersion: "3.10.12"
    buildCommand: |
      python -m pip install --upgrade pip
      pip install setuptools==68.0.0
      pip install -r requirements.txt
    startCommand: streamlit run mental_health_app.py --server.port=$PORT --server.address=0.0.0.0